### ISSUE TITLE
3.4.0 packaging regression: CUDA libs packed with the main JAR

### ISSUE THREAD

**Issue by shuttie** [kherud/java-llama.cpp#76]
So the no-classifier JAR still seems to bundle the CUDA libs for some reason:

![image](https://github.com/user-attachments/assets/5948c6b9-b0d6-4b1b-adf8-eb31ea0415f9)

So it means that the official 3.4.0 JAR might not work on non-CUDA environments :(

**Comment by kherud** [comment]
I think the reason is this part of the earlier release workflow code:

```
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/src/main/resources/de/kherud/llama/
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/src/main/resources_linux_cuda/de/kherud/llama/
```

Both CPU and GPU artifacts used the same name, and the latter probably overwrote the former silently. Coincidentally, I just upgraded the workflow to use newer versions for the upload and download actions, which should fix the problem, I think. I'll create a second release in a second.
